### ISSUE TITLE
US #33 Placed Objects for Level 1 Gameplay

### ISSUE THREAD

**Issue by rajkieran** [paceuniversity/CS3892017team5#14]
As a developer, I need to create Level 1 specialty objects and place the applicable objects for the first level (need to specify what they are), so that I am able to create the first level.

**Comment by mcclurehayden** [comment]
Updated assignees and label.

**Comment by mcclurehayden** [comment]
Kasey, please add the Tasks for this User Story, following the format Raj and I set-up.

**Comment by Fisixnstuff** [comment]
US#33 Task 1 Sketch for Level 1 #47  Comepleted.

**Comment by mcclurehayden** [comment]
First level is pretty much done.
