### ISSUE TITLE
User Story #32 Objects for Core Gameplay

### ISSUE THREAD

**Issue by Fisixnstuff** [paceuniversity/CS3892017team5#16]
As a developer, I want to create the core objects (tiles, obstacles, backgrounds) necessary for basic game play so that I can build the levels.

**Comment by rajkieran** [comment]
The player and platforms are done thus far. More objects need to be made for diverse gameplay.

**Comment by mcclurehayden** [comment]
In a way this got finished without ever getting tackled, we just have one level which will eventually change, will it?
