### ISSUE TITLE
User Story #42 Working Git Hub Repository

### ISSUE THREAD

**Issue by mcclurehayden** [paceuniversity/CS3892017team5#31]
As a developer, I want to have all my code in Git Hub and set-up with organized branches so that my fellow developers can easily share changes and we avoid merge conflicts.

**Comment by rajkieran** [comment]
GitHub rep was organized and cleaned up. The team should now be aware of the system in place to keep everyone's branches up-to-date and keep the development branch stable.

**Comment by mcclurehayden** [comment]
This is mostly considered done, enters the maintenance phase now. Just need to make sure we can keep the repository neat, together, and functioning.
