### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by scharffc** [paceuniversity/CS3892017team5#4]
Please add the pics.

The picture you put for architecture is more like a UI. This is not an architecture. Please remove it. It is anyway in the requirements discovery document.

**Comment by mcclurehayden** [comment]
Removed the incorrect architecture picture. Photos of us still need to be added, if our team wants to add them. We will discuss at our next meeting.

**Comment by mcclurehayden** [comment]
The architecture issues had been addressed, we will be adding a group photo tomorrow, shortly before class.
