### ISSUE TITLE
Feedback on Sprint 1 Goal

### ISSUE THREAD

**Issue by scharffc** [paceuniversity/CS3892017team5#6]
The Sprint 1 Goal is missing.

I got the email for the extension.

You need to be more decisive in your work. Delaying the planning affects your whole sprint.

**Comment by mcclurehayden** [comment]
Thanks for your understanding, the goal has been addressed. Due to time, we never fully decomposed these things into tasks. Our user stories were smaller. We will address this for the next Sprint.
