### ISSUE TITLE
User Story #25 Narrative for Level 1

### ISSUE THREAD

**Issue by Fisixnstuff** [paceuniversity/CS3892017team5#9]
As a player, I want to have an understanding of the student protest part of the narrative through text prior to playing the first level, so that I feel that my game play has context and meaning.

**Comment by Fisixnstuff** [comment]
Outline for occupation has been done.
Events for level 1 have been created.
Event Scripts still in progress.

**Comment by mcclurehayden** [comment]
Kasey now that this is done, after the first sprint, I am closing this issue.
